version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.10.1
  # katalon-studio: katalon/katalon-studio@23.0.11

jobs:
  run_unittests:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm run test
  deploy_staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  run_tests:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Staging Test Suit
          command: cd test_katalon && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/TS_Staging" -executionProfile="default" -browserType="Chrome (headless)" --apiKey=$KATALON_API_KEY
      - run:
          name: Execute Katalon Staging Test Suit
          command: cd test_katalon && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/Data_driven" -executionProfile="default" -browserType="Chrome (headless)" --apiKey=$KATALON_API_KEY
      - run:
          name: Execute Katalon Staging Test Suit
          command: cd test_katalon && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/Record_playback" -executionProfile="default" -browserType="Chrome (headless)" --apiKey=$KATALON_API_KEY
  deploy:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run:
          name: Trigger host deployment
          command: |
            curl $DEPLOY_HOOK
            echo 'Triggered deploy'
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  build-run-and-test:
    jobs:
      - run_unittests
      - deploy_staging:
          requires:
            - run_unittests
          filters:
            branches:
              only:
                - main
      - run_tests:
          requires:
            - deploy_staging
      # - katalon-studio/run:
      #     version: "latest"
      #     command_arguments: '-browserType="Chrome" -retry=2 -statusDelay=15 -projectPath="/root/project/test_katalon" -testSuitePath="Test Suites/TS_Staging"'
      #     requires:
      #       - deploy_staging
      - deploy:
          context: slack-secrets
          requires:
            - run_tests
            # - katalon-studio/run
            # - run_unittests
          # filters:
          #   branches:
          #     only:
          #       - main         
