version: 2.1

orbs:
  node: circleci/node@4.7
  heroku: circleci/heroku@1.2.6
  slack: circleci/slack@4.10.1

jobs:
  run_unittests:
    docker:
      - image: cimg/node:14.15.3
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm install --save
      - run:
          name: Run Unit Tests
          command: |
            npm run test
      - slack/notify:
          event: fail
          template: basic_fail_1
  deploy_staging:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
  run_tests:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Staging Test Suit
          command: cd test_katalon && katalon-execute.sh -statusDelay=30 -retry=0 -testSuitePath="Test Suites/TS_Staging" -executionProfile="default" -browserType="Chrome (headless)" --apiKey=$KATALON_API_KEY
      - slack/notify:
          event: fail
          template: basic_fail_1
  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - run:
          name: Trigger host deployment
          command: |
            curl $DEPLOY_HOOK
            echo 'Triggered deploy'
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  build-run-and-test:
    jobs:
      - run_unittests:
          context: slack-secrets
      - deploy_staging:
          requires:
            - run_unittests
          filters:
            branches:
              only:
                - main
      - run_tests:
          context: slack-secrets
          requires:
            - deploy_staging
      - deploy:
          context: slack-secrets
          requires:
            - run_tests
