<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_about</name>
   <tag></tag>
   <elementGuidId>100ba00d-2805-4e62-84b7-2b36cb7273b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6 > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div[3]/div/div/h6/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1df0b094-e8c6-4ef5-821d-94de59b93ea9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/about</value>
      <webElementGuid>fccd42ec-2ef5-4423-bf98-984da2b4cb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>about</value>
      <webElementGuid>bd777bae-e55d-475e-ba53-d93e1637c1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;home container-fluid&quot;]/div[@class=&quot;info-div&quot;]/div[@class=&quot;info&quot;]/div[@class=&quot;info-about&quot;]/h6[1]/a[1]</value>
      <webElementGuid>e9e8fe2d-bb4d-4f2f-9ae4-66cc1e3a46a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div[3]/div/div/h6/a</value>
      <webElementGuid>6124e871-86f3-4c12-badc-15f5db4ff015</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'about')]</value>
      <webElementGuid>73587ca6-ea3f-4343-a00e-af573aa0d68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Let', &quot;'&quot;, 's find you something to do')])[1]/following::a[1]</value>
      <webElementGuid>66bb4ee3-ee5d-43d1-9fe7-943159781cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='documentation'])[1]/preceding::a[1]</value>
      <webElementGuid>c0f8a9b5-f683-4fc9-844f-5f112c706144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='about']/parent::*</value>
      <webElementGuid>896db3d0-22af-41b7-b3b7-60d66a67e617</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/about')])[2]</value>
      <webElementGuid>7fb808fd-3c10-4b20-b5ad-5fe8bb9c4386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6/a</value>
      <webElementGuid>6e2f79e4-ee2b-452f-bbc5-ddf65e05337b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/about' and (text() = 'about' or . = 'about')]</value>
      <webElementGuid>dbd70688-f6d0-42bd-aa43-27fbc5ddbbe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
